CREATE TABLE `CAT_MARGEN` (
  `CVE_MARGEN` decimal(2,0) NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  PRIMARY KEY (`CVE_MARGEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_MARGEN` (`CVE_MARGEN`, `DESCRIPCION`)
VALUES
	(1, 'DERECHO'),
	(2, 'IZQUIERDO');
