CREATE TABLE `CAT_DERECHOS_TRANSITO` (
  `CVE_CDT` decimal(2,0) NOT NULL,
  `NOMBRE` varchar(13) NOT NULL,
  PRIMARY KEY (`CVE_CDT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_DERECHOS_TRANSITO` (`CVE_CDT`, `NOMBRE`)
VALUES
	(1, 'CUOTA'),
	(2, 'LIBRE'),
	(3, '');
