CREATE TABLE `CAT_ADMINISTRACION` (
  `CVE_CAC` decimal(1,0) NOT NULL,
  `NOMBRE` varchar(20) NOT NULL,
  PRIMARY KEY (`CVE_CAC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_ADMINISTRACION` (`CVE_CAC`, `NOMBRE`)
VALUES
	(1, 'ESTATAL'),
	(2, 'FEDERAL'),
	(3, 'MUNICIPAL'),
	(4, 'PARTICULAR'),
	(5, '');
