CREATE TABLE `CAT_SINCO_GRUPO` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(120) DEFAULT NULL,
  `id_cat_sinco_division` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

INSERT INTO `CAT_SINCO_GRUPO` (`id`, `nombre`, `id_cat_sinco_division`)
VALUES
	(11, 'Funcionarios y altas autoridades de los sectores público, privado y social', 1),
	(12, 'Directores y gerentes en servicios financieros, administrativos y sociales', 1),
	(13, 'Directores y gerentes en producción, tecnología y transporte', 1),
	(14, 'Directores y gerentes de ventas, restaurantes, hoteles y otros establecimientos', 1),
	(15, 'Coordinadores y jefes de área en servicios financieros, administrativos y sociales', 1),
	(16, 'Coordinadores y jefes de área en producción y tecnología', 1),
	(17, 'Coordinadores y jefes de área de ventas, restaurantes, hoteles y otros establecimientos', 1),
	(19, 'Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente                  ', 1),
	(21, 'Especialistas en ciencias económico-administrativas, ciencias sociales, humanistas y en artes', 2),
	(22, 'Investigadores  y  especialistas en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones', 2),
	(23, 'Profesores y especialistas en docencia', 2),
	(24, 'Médicos, enfermeras y otros especialistas en salud', 2),
	(25, 'Auxiliares y técnicos en ciencias económico-administrativas, ciencias sociales, humanistas y en artes', 2),
	(26, 'Auxiliares y técnicos en ciencias exactas, biológicas, ingeniería, informática y en telecomunicaciones', 2),
	(27, 'Auxiliares y técnicos en educación, instructores y capacitadores', 2),
	(28, 'Enfermeras, técnicos en medicina y trabajadores de apoyo en salud', 2),
	(29, 'Otros especialistas y técnicos, no clasificados anteriormente', 2),
	(31, 'Secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte', 3),
	(32, 'Trabajadores que brindan y manejan información', 3),
	(39, 'Otras secretarias, capturistas, cajeros y trabajadores que brindan información, no clasificados anteriormente', 3),
	(41, 'Comerciantes en establecimientos', 4),
	(42, 'Empleados de ventas en establecimientos', 4),
	(43, 'Trabajadores en el alquiler', 4),
	(49, 'Otros comerciantes, empleados en ventas y agentes de ventas en establecimientos, no clasificados anteriormente', 4),
	(51, 'Trabajadores en la preparación y servicio de alimentos y bebidas en establecimientos', 5),
	(52, 'Trabajadores en cuidados personales y del hogar', 5),
	(53, 'Trabajadores en servicios de protección y vigilancia', 5),
	(54, 'Trabajadores de las fuerzas armadas', 5),
	(59, 'Otras ocupaciones en servicios personales y vigilancia, no clasificadas anteriormente', 5),
	(61, 'Trabajadores en actividades agrícolas y ganaderas', 6),
	(62, 'Trabajadores en actividades pesqueras, forestales, caza y similares', 6),
	(63, 'Operadores de maquinaria agropecuaria y  forestal', 6),
	(69, 'Otros trabajadores en actividades agrícolas, ganaderas, forestales, caza y pesca, no clasificados anteriormente', 6),
	(71, 'Trabajadores en la extracción y la edificación de construcciones', 7),
	(72, 'Artesanos y trabajadores en el tratamiento y elaboración de productos de metal  ', 7),
	(73, 'Artesanos y trabajadores en la elaboración de productos de madera, papel, textiles y de cuero y piel ', 7),
	(74, 'Artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas  ', 7),
	(75, 'Trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco  ', 7),
	(76, 'Artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares  ', 7),
	(79, 'Otros trabajadores artesanales, no clasificados anteriormente', 7),
	(81, 'Operadores de  instalaciones y maquinaria industrial', 8),
	(82, 'Ensambladores y montadores de herramientas, maquinaria, productos metálicos y electrónicos', 8),
	(83, 'Conductores de transporte y de maquinaria móvil', 8),
	(89, 'Otros operadores de maquinaria industrial, ensambladores y conductores de transporte, no clasificados anteriormente', 8),
	(91, 'Trabajadores de apoyo en actividades agropecuarias, forestales, pesca y caza', 9),
	(92, 'Trabajadores de apoyo en la minería, construcción e industria', 9),
	(93, 'Ayudantes de conductores de transporte, conductores de transporte de tracción humana y animal y cargadores', 9),
	(94, 'Ayudantes en la preparación de alimentos ', 9),
	(95, 'Vendedores ambulantes ', 9),
	(96, 'Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza', 9),
	(97, 'Trabajadores de paquetería, de apoyo para espectáculos y repartidores de mercancías', 9),
	(98, 'Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente ', 9),
	(99, 'Ocupaciones no especificadas', 9);
