CREATE TABLE `CAT_SINCO_SUBGRUPO` (
  `cve` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(250) DEFAULT NULL,
  `cve_grupo` int(11) DEFAULT NULL,
  `cve_division` int(11) DEFAULT NULL,
  PRIMARY KEY (`cve`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

INSERT INTO `CAT_SINCO_SUBGRUPO` (`cve`, `nombre`, `cve_grupo`, `cve_division`)
VALUES
	(111, 'Funcionarios legisladores y autoridades gubernamentales', 11, 1),
	(112, 'Presidentes y directores generales', 11, 1),
	(113, 'Directores de organizaciones políticas, sindicales y civiles', 11, 1),
	(121, 'Directores y gerentes en servicios financieros y administrativos', 12, 1),
	(122, 'Directores y gerentes en servicios de salud, enseñanza y sociales', 12, 1),
	(131, 'Directores y gerentes en producción agropecuaria, industrial, construcción y mantenimiento', 13, 1),
	(132, 'Directores y gerentes en informática, telecomunicaciones, transporte y en investigación y desarrollo tecnológico', 13, 1),
	(141, 'Directores y gerentes de ventas, restaurantes y hoteles', 14, 1),
	(142, 'Directores y gerentes de museos, cines y otros establecimientos', 14, 1),
	(151, 'Coordinadores y jefes de área en servicios financieros y administrativos', 15, 1),
	(152, 'Coordinadores y jefes de área en servicios de salud, enseñanza, sociales y jueces calificadores', 15, 1),
	(161, 'Coordinadores y jefes de área en producción agropecuaria, industrial, construcción y mantenimiento', 16, 1),
	(162, 'Coordinadores y jefes de área en informática, telecomunicaciones, transporte y en investigación  y desarrollo tecnológico  ', 16, 1),
	(171, 'Coordinadores y jefes de área de ventas, restaurantes y hoteles', 17, 1),
	(172, 'Coordinadores y jefes de área en museos, cines y otros establecimientos', 17, 1),
	(199, 'Otros directores, funcionarios, gerentes, coordinadores y jefes de área, no clasificados anteriormente                                      ', 19, 1),
	(211, 'Administradores y mercadólogos', 21, 2),
	(212, 'Contadores, auditores, especialistas en finanzas y en economía', 21, 2),
	(213, 'Investigadores y especialistas en ciencias sociales', 21, 2),
	(214, 'Investigadores y especialistas en ciencias humanistas', 21, 2),
	(215, 'Autores, periodistas y traductores', 21, 2),
	(216, 'Pintores, diseñadores y dibujantes artísticos, escultores y escenógrafos', 21, 2),
	(217, 'Artistas interpretativos', 21, 2),
	(221, 'Investigadores y especialistas en física, matemáticas, estadística y actuaría', 22, 2),
	(222, 'Investigadores y especialistas en ciencias biológicas, químicas y del medio ambiente', 22, 2),
	(223, 'Especialistas en ciencias agronómicas', 22, 2),
	(224, 'Ingenieros eléctricos y en electrónica', 22, 2),
	(225, 'Ingenieros químicos, mecánicos, industriales, mineros y metalúrgicos', 22, 2),
	(226, 'Ingenieros civiles, topógrafos y arquitectos', 22, 2),
	(227, 'Investigadores y especialistas en sistemas computacionales', 22, 2),
	(228, 'Ingenieros en comunicaciones y telecomunicaciones', 22, 2),
	(231, 'Supervisores educativos y especialistas en ciencias de la educación', 23, 2),
	(232, 'Profesores de nivel medio y superior', 23, 2),
	(233, 'Profesores de nivel básico', 23, 2),
	(234, 'Profesores en enseñanza especial', 23, 2),
	(239, 'Otros profesores y especialistas en docencia, no clasificados anteriormente', 23, 2),
	(241, 'Médicos generales y especialistas', 24, 2),
	(242, 'Otros especialistas en salud', 24, 2),
	(251, 'Auxiliares en administración, contabilidad y finanzas', 25, 2),
	(252, 'Inspectores públicos', 25, 2),
	(253, 'Auxiliares en ciencias sociales y humanistas', 25, 2),
	(254, 'Diseñadores de modas, industriales, gráficos y decoradores de interiores', 25, 2),
	(255, 'Locutores, animadores y payasos', 25, 2),
	(256, 'Deportistas, entrenadores y árbitros', 25, 2),
	(261, 'Auxiliares y técnicos en ciencias físicas, matemáticas, biológicas, químicas, del medio ambiente y agronómicas', 26, 2),
	(262, 'Auxiliares y técnicos industriales, topógrafos, mineros y dibujantes técnicos', 26, 2),
	(263, 'Mecánicos y técnicos en mantenimiento y reparación de equipos mecánicos, vehículos de motor, instrumentos industriales y equipo de refrigeración', 26, 2),
	(264, 'Técnicos eléctricos, en electrónica y de equipos en telecomunicaciones y electromecánicos', 26, 2),
	(265, 'Auxiliares y técnicos en informática y en equipos de comunicaciones y grabación', 26, 2),
	(266, 'Controladores de tráfico aéreo y de otros transportes', 26, 2),
	(271, 'Auxiliares y técnicos en educación, instructores y capacitadores', 27, 2),
	(281, 'Enfermeras y técnicos en medicina', 28, 2),
	(282, 'Trabajadores de apoyo en  salud', 28, 2),
	(299, 'Otros especialistas y técnicos, no clasificados anteriormente', 29, 2),
	(310, 'Supervisores de secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte', 31, 3),
	(311, 'Secretarias, taquígrafos, mecanógrafos, capturistas de datos y operadores de máquinas de oficina', 31, 3),
	(312, 'Cajeros, cobradores y pagadores', 31, 3),
	(313, 'Trabajadores en archivo y control de almacén y bodega', 31, 3),
	(314, 'Trabajadores en el control de la operación de transporte', 31, 3),
	(320, 'Supervisores de trabajadores que brindan y manejan información', 32, 3),
	(321, 'Recepcionistas, trabajadores que brindan información y telefonistas', 32, 3),
	(322, 'Trabajadores en agencias de viajes e información  turística', 32, 3),
	(323, 'Encuestadores y codificadores', 32, 3),
	(399, 'Otras secretarias, capturistas, cajeros y trabajadores que brindan información, no clasificados anteriormente', 39, 3),
	(411, 'Comerciantes en establecimientos', 41, 4),
	(420, 'Encargados y supervisores de ventas de productos y de servicios financieros y de alquiler', 42, 4),
	(421, 'Empleados de ventas y vendedores por teléfono', 42, 4),
	(422, 'Agentes, representantes de ventas y vendedores por catálogo', 42, 4),
	(423, 'Trabajadores en la promoción de ventas y modelos', 42, 4),
	(431, 'Trabajadores en el alquiler', 43, 4),
	(499, 'Otros comerciantes, empleados en ventas y agentes de ventas en establecimientos, no clasificados anteriormente', 49, 4),
	(510, 'Supervisores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería', 51, 5),
	(511, 'Trabajadores en la preparación y servicio de alimentos y bebidas en establecimientos', 51, 5),
	(520, 'Supervisores y encargados de trabajadores en cuidados personales y del hogar ', 52, 5),
	(521, 'Peluqueros, embellecedores y similares', 52, 5),
	(522, 'Trabajadores en el cuidado de personas', 52, 5),
	(523, 'Azafatas y sobrecargos', 52, 5),
	(524, 'Jardineros', 52, 5),
	(525, 'Trabajadores en otros servicios personales', 52, 5),
	(530, 'Supervisores en servicios de protección y vigilancia', 53, 5),
	(531, 'Trabajadores en servicios de protección y vigilancia', 53, 5),
	(540, 'Supervisores de las fuerzas armadas', 54, 5),
	(541, 'Trabajadores de las fuerzas armadas', 54, 5),
	(599, 'Otras ocupaciones en servicios personales y vigilancia, no clasificadas anteriormente', 59, 5),
	(610, 'Supervisores, encargados y capataces agropecuarios', 61, 6),
	(611, 'Trabajadores en actividades agrícolas', 61, 6),
	(612, 'Trabajadores en actividades ganaderas y en la cría de animales', 61, 6),
	(613, 'Trabajadores que combinan actividades agrícolas con ganaderas', 61, 6),
	(620, 'Supervisores, encargados y capataces de trabajadores en actividades pesqueras, acuícolas, forestales, caza y similares', 62, 6),
	(621, 'Trabajadores en actividades pesqueras y de acuacultura', 62, 6),
	(622, 'Trabajadores en actividades silvícolas y forestales', 62, 6),
	(623, 'Trabajadores en actividades de caza, trampería y similares', 62, 6),
	(631, 'Operadores de maquinaria agropecuaria y  forestal', 63, 6),
	(699, 'Otros trabajadores en actividades agrícolas, ganaderas, forestales, caza y pesca, no clasificados anteriormente', 69, 6),
	(710, 'Supervisores de trabajadores en la extracción, albañiles y en acabados de la construcción', 71, 7),
	(711, 'Trabajadores en la extracción', 71, 7),
	(712, 'Albañiles y otros trabajadores en la edificación de construcciones', 71, 7),
	(713, 'Yeseros, instaladores de pisos, climas, impermeabilizante, vidrio, etc., plomeros y pintores', 71, 7),
	(720, 'Supervisores de artesanos y trabajadores en el tratamiento y elaboración de productos de metal', 72, 7),
	(721, 'Moldeadores, soldadores, hojalateros y pintores de metales ', 72, 7),
	(722, 'Herreros, cerrajeros, joyeros y artesanos en la elaboración de productos de metal', 72, 7),
	(730, 'Supervisores de artesanos y trabajadores en la elaboración de productos de madera, papel, textiles y de cuero y piel', 73, 7),
	(731, 'Artesanos y trabajadores en la elaboración de productos de madera', 73, 7),
	(732, 'Artesanos y trabajadores en la elaboración de productos de papel, cartón y trabajos de impresión', 73, 7),
	(733, 'Tejedores y trabajadores en la preparación de fibras textiles', 73, 7),
	(734, 'Artesanos y trabajadores en la elaboración de productos textiles ', 73, 7),
	(735, 'Tapiceros y trabajadores en el tratamiento y elaboración de productos de cuero y piel ', 73, 7),
	(740, 'Supervisores de artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas ', 74, 7),
	(741, 'Artesanos y trabajadores en la elaboración de productos de hule, caucho, plásticos y de sustancias químicas ', 74, 7),
	(750, 'Supervisores de trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco', 75, 7),
	(751, 'Trabajadores en la elaboración y procesamiento de alimentos, bebidas y productos de tabaco  ', 75, 7),
	(760, 'Supervisores de artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares', 76, 7),
	(761, 'Artesanos y trabajadores en la elaboración de productos de cerámica, vidrio, azulejo y similares ', 76, 7),
	(799, 'Otros trabajadores artesanales, no clasificados anteriormente', 79, 7),
	(810, 'Supervisores de operadores de maquinaria industrial', 81, 8),
	(811, 'Operadores de máquinas y equipos para la extracción en minas, canteras y pozos', 81, 8),
	(812, 'Operadores de máquinas y equipos en la fabricación metalúrgica, fabricación de maquinaria y productos metálicos', 81, 8),
	(813, 'Operadores de máquinas y equipos en la elaboración de productos químicos, plásticos, tratamiento de agua y petroquímica', 81, 8),
	(814, 'Operadores de máquinas para la madera y papel', 81, 8),
	(815, 'Operadores de máquinas y equipos en la elaboración de productos textiles, cuero y piel', 81, 8),
	(816, 'Operadores de máquinas en la elaboración de alimentos, bebidas y tabaco', 81, 8),
	(817, 'Operadores de máquinas en la elaboración de cemento y productos de cerámica, vidrio y similares', 81, 8),
	(818, 'Operadores de máquinas para la generación de energía', 81, 8),
	(819, 'Otros operadores de instalaciones y maquinaria fija industrial, no clasificados anteriormente', 81, 8),
	(820, 'Supervisores en procesos de ensamblado y montaje de  maquinaria, herramientas y productos metálicos y electrónicos', 82, 8),
	(821, 'Ensambladores y montadores de  herramientas, maquinaria, productos metálicos y electrónicos', 82, 8),
	(830, 'Supervisores de conductores de transporte y de maquinaria móvil', 83, 8),
	(831, 'Conductores de transporte aéreo ', 83, 8),
	(832, 'Conductores de transporte marítimo', 83, 8),
	(833, 'Conductores de transporte en vías férreas', 83, 8),
	(834, 'Conductores de transporte terrestre con motor', 83, 8),
	(835, 'Conductores de maquinaria móvil ', 83, 8),
	(899, 'Otros operadores de maquinaria industrial, ensambladores y conductores de transporte, no clasificados anteriormente', 89, 8),
	(911, 'Trabajadores de apoyo en actividades agropecuarias', 91, 9),
	(912, 'Trabajadores de apoyo en actividades forestales, pesca y caza', 91, 9),
	(921, 'Trabajadores de apoyo en la minería y extracción', 92, 9),
	(922, 'Trabajadores de apoyo en la construcción  y la plomería', 92, 9),
	(923, 'Trabajadores de apoyo en la industria', 92, 9),
	(931, 'Ayudantes de conductores de transporte', 93, 9),
	(932, 'Conductores de transporte en bicicleta y animal', 93, 9),
	(933, 'Cargadores', 93, 9),
	(941, 'Ayudantes en la preparación de alimentos', 94, 9),
	(951, 'Vendedores ambulantes (excluyendo los de venta de alimentos)', 95, 9),
	(952, 'Vendedores ambulantes de alimentos', 95, 9),
	(960, 'Supervisores en limpieza, amas de llaves, mayordomos y en estacionamientos', 96, 9),
	(961, 'Trabajadores domésticos', 96, 9),
	(962, 'Trabajadores de limpieza, recamaristas, mozos de limpieza y limpiadores de calzado', 96, 9),
	(963, 'Lavadores y cuidadores de vehículos', 96, 9),
	(964, 'Lavanderos y planchadores', 96, 9),
	(965, 'Ayudantes de jardineros', 96, 9),
	(966, 'Recolectores de desechos, material reciclable y otros materiales', 96, 9),
	(971, 'Trabajadores de paquetería, empacado y de apoyo para espectáculos', 97, 9),
	(972, 'Trabajadores repartidores de mensajería y mercancías (a pie y en bicicleta)', 97, 9),
	(973, 'Lecturistas de medidores, recolectores de dinero y elevadoristas', 97, 9),
	(989, 'Otros trabajadores en actividades elementales y de apoyo, no clasificados anteriormente ', 98, 9),
	(999, 'Ocupaciones no especificadas', 99, 9);
