CREATE TABLE `CAT_TIPO_DOM` (
  `CVE_TIPO_DOM` decimal(1,0) NOT NULL,
  `DESCRIPCION` varchar(240) NOT NULL,
  `COMP_ESPAC` varchar(240) NOT NULL,
  PRIMARY KEY (`CVE_TIPO_DOM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_TIPO_DOM` (`CVE_TIPO_DOM`, `DESCRIPCION`, `COMP_ESPAC`)
VALUES
	(1, 'DOMICILIO URBANO', 'VIALIDAD'),
	(2, 'DOMICILIO RURAL', 'VIALIDAD'),
	(3, 'VIAS DE COMUNICACIÓN', 'CARRETERA'),
	(4, 'VIAS DE COMUNICACIÓN', 'CAMINO');
