CREATE TABLE `CAT_AMBITO` (
  `AMBITO` decimal(1,0) NOT NULL,
  `NOMBRE` varchar(30) NOT NULL,
  PRIMARY KEY (`AMBITO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_AMBITO` (`AMBITO`, `NOMBRE`)
VALUES
	(1, 'URBANO'),
	(2, 'RURAL');
