CREATE TABLE `CAT_VIALIDAD` (
  `CVE_TIPO_VIAL` decimal(10,0) NOT NULL,
  `DESCRIPCION` varchar(255) NOT NULL,
  PRIMARY KEY (`CVE_TIPO_VIAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_VIALIDAD` (`CVE_TIPO_VIAL`, `DESCRIPCION`)
VALUES
	(1, 'AMPLIACIÓN'),
	(2, 'ANDADOR'),
	(3, 'AVENIDA'),
	(4, 'BOULEVARD'),
	(5, 'CALLE'),
	(6, 'CALLEJÓN'),
	(7, 'CALZADA'),
	(8, 'CERRADA'),
	(9, 'CIRCUITO'),
	(10, 'CIRCUNVALACIÓN'),
	(11, 'CONTINUACIÓN'),
	(12, 'CORREDOR'),
	(13, 'DIAGONAL'),
	(14, 'EJE VIAL'),
	(15, 'PASAJE'),
	(16, 'PEATONAL'),
	(17, 'PERIFÉRICO'),
	(18, 'PRIVADA'),
	(19, 'PROLONGACIÓN'),
	(20, 'RETORNO'),
	(21, 'VIADUCTO'),
	(22, 'NINGUNO');
