CREATE TABLE `CAT_TERM_GEN` (
  `CVE_TER` decimal(2,0) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  PRIMARY KEY (`CVE_TER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_TERM_GEN` (`CVE_TER`, `NOMBRE`)
VALUES
	(1, 'CARRETERA'),
	(2, 'CAMINO'),
	(3, 'TERRACERIA'),
	(4, 'BRECHA'),
	(5, 'VEREDA');
