CREATE TABLE `DOMICILIOS_CAMINOS` (
  `DOMICILIO_ID` int(11) NOT NULL,
  `NOMVIAL` varchar(240) NOT NULL,
  `ORIGEN` varchar(255) DEFAULT NULL,
  `DESTINO` varchar(255) DEFAULT NULL,
  `CADENAMIENTO` varchar(255) DEFAULT NULL,
  `CVE_TER` decimal(2,0) NOT NULL,
  `CVE_MARGEN` decimal(2,0) DEFAULT NULL,
  PRIMARY KEY (`DOMICILIO_ID`),
  KEY `DCO_CTGG_FK` (`CVE_TER`),
  KEY `DCO_CMN_FK` (`CVE_MARGEN`),
  CONSTRAINT `DCO_CMN_FK` FOREIGN KEY (`CVE_MARGEN`) REFERENCES `CAT_MARGEN` (`CVE_MARGEN`),
  CONSTRAINT `DCO_CTGG_FK` FOREIGN KEY (`CVE_TER`) REFERENCES `CAT_TERM_GEN` (`CVE_TER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;