CREATE TABLE `DOMICILIOS_RURALES` (
  `DOMICILIO_ID` int(11) NOT NULL,
  `CVE_VIA` decimal(10,0) NOT NULL,
  PRIMARY KEY (`DOMICILIO_ID`),
  KEY `DRE_VIDD_FK` (`CVE_VIA`),
  CONSTRAINT `DRE_VIDD_FK` FOREIGN KEY (`CVE_VIA`) REFERENCES `VIALIDAD` (`CVE_VIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;