CREATE TABLE `VIALIDAD` (
  `CVE_VIA` decimal(10,0) NOT NULL,
  `CVE_ENT` varchar(2) NOT NULL,
  `CVE_MUN` varchar(3) NOT NULL,
  `CVE_LOC` varchar(4) NOT NULL,
  `CVE_PERIODO` decimal(2,0) NOT NULL,
  `NOM_VIA` varchar(255) NOT NULL,
  `CVE_TIPO_VIAL` decimal(10,0) NOT NULL,
  `AGREGADA` char(1) DEFAULT NULL,
  `AMBITO` decimal(1,0) NOT NULL,
  PRIMARY KEY (`CVE_VIA`),
  KEY `VIDD_CVDU_FK` (`CVE_TIPO_VIAL`),
  KEY `VIDD_CAOA_FK` (`AMBITO`),
  CONSTRAINT `VIDD_CAOA_FK` FOREIGN KEY (`AMBITO`) REFERENCES `CAT_AMBITO` (`AMBITO`),
  CONSTRAINT `VIDD_CVDU_FK` FOREIGN KEY (`CVE_TIPO_VIAL`) REFERENCES `CAT_VIALIDAD` (`CVE_TIPO_VIAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;